### Libraries

In [137]:
import os
import tensorflow as tf
from tensorflow.keras.preprocessing.image import img_to_array
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import sklearn

### Load data

In [3]:
df = pd.read_csv(r'Data_Entry_2017_v2020.csv')
df.head()

Image Index          Finding Labels  Follow-up #  Patient ID  \
0  00000001_000.png            Cardiomegaly            0           1   
1  00000001_001.png  Cardiomegaly|Emphysema            1           1   
2  00000001_002.png   Cardiomegaly|Effusion            2           1   
3  00000002_000.png              No Finding            0           2   
4  00000003_001.png                  Hernia            0           3   

   Patient Age Patient Gender View Position  OriginalImage[Width  Height]  \
0           57              M            PA                 2682     2749   
1           58              M            PA                 2894     2729   
2           58              M            PA                 2500     2048   
3           80              M            PA                 2500     2048   
4           74              F            PA                 2500     2048   

   OriginalImagePixelSpacing[x     y]  
0                        0.143  0.143  
1                        0.143  0.143  
2                        0.168  0.168  
3                        0.171  0.171  
4                        0.168  0.168

### Load images

In [12]:
path = 'C:\\Users\\stan\\chest_images\\'
dir_ = os.listdir(path)
images, key = [], []
for (i, image) in enumerate(dir_[:5000]):
    im_dir = path + str(image)
    key.append(image)
    images.append(tf.keras.preprocessing.image.load_img(im_dir))

#### Resizing images

In [13]:
px = 32
for i, image in enumerate(images):
    images[i] = image.resize((px, px))

#### Images to array

In [14]:
img = []
for i, image in enumerate(images):
    img.append(img_to_array(image))

In [15]:
data = np.array(img)
data.shape

(5000, 32, 32, 3)

### Age, Gender and View Position

In [88]:
df2 = pd.DataFrame(key)
df2.rename(columns = {0 : 'Image Index'}, inplace = True)
df2 = df2.merge(df[["Finding Labels", "Patient ID", "Patient Age", "Patient Gender", "View Position"]], \
          left_on = "Image Index", right_on = df["Image Index"])
df2.head()

Image Index          Finding Labels  Patient ID  Patient Age  \
0  00000001_000.png            Cardiomegaly           1           57   
1  00000001_001.png  Cardiomegaly|Emphysema           1           58   
2  00000001_002.png   Cardiomegaly|Effusion           1           58   
3  00000002_000.png              No Finding           2           80   
4  00000003_000.png                  Hernia           3           81   

  Patient Gender View Position  
0              M            PA  
1              M            PA  
2              M            PA  
3              M            PA  
4              F            PA

#### Gender

In [89]:
df2["M"] = None
df2["F"] = None
for i, gender in enumerate(df2["Patient Gender"].values):
    if gender == "M":
        df2["M"][i] = 1
        df2["F"][i] = 0
    else:
        df2["M"][i] = 0
        df2["F"][i] = 1
df2.drop("Patient Gender", axis = 1, inplace = True)
df2.head()

c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
c:\user

Image Index          Finding Labels  Patient ID  Patient Age  \
0  00000001_000.png            Cardiomegaly           1           57   
1  00000001_001.png  Cardiomegaly|Emphysema           1           58   
2  00000001_002.png   Cardiomegaly|Effusion           1           58   
3  00000002_000.png              No Finding           2           80   
4  00000003_000.png                  Hernia           3           81   

  View Position  M  F  
0            PA  1  0  
1            PA  1  0  
2            PA  1  0  
3            PA  1  0  
4            PA  0  1

In [115]:
df[]

Image Index          Finding Labels  Follow-up #  Patient ID  \
0  00000001_000.png            Cardiomegaly            0           1   
1  00000001_001.png  Cardiomegaly|Emphysema            1           1   
2  00000001_002.png   Cardiomegaly|Effusion            2           1   
3  00000002_000.png              No Finding            0           2   
4  00000003_001.png                  Hernia            0           3   

   Patient Age Patient Gender View Position  OriginalImage[Width  Height]  \
0           57              M            PA                 2682     2749   
1           58              M            PA                 2894     2729   
2           58              M            PA                 2500     2048   
3           80              M            PA                 2500     2048   
4           74              F            PA                 2500     2048   

   OriginalImagePixelSpacing[x     y]  M  F PA AP  
0                        0.143  0.143  1  0  1  0  
1                        0.143  0.143  1  0  1  0  
2                        0.168  0.168  1  0  1  0  
3                        0.171  0.171  1  0  1  0  
4                        0.168  0.168  0  1  1  0

#### View position

In [90]:
df2["PA"] = None
df2["AP"] = None
for i, pos in enumerate(df2["View Position"].values):
    if pos == "AP":
        df2["AP"][i] = 1
        df2["PA"][i] = 0
    else:
        df2["AP"][i] = 0
        df2["PA"][i] = 1
df2.drop("View Position", axis = 1, inplace = True)
df2.head()

c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-v

Image Index          Finding Labels  Patient ID  Patient Age  M  F PA  \
0  00000001_000.png            Cardiomegaly           1           57  1  0  1   
1  00000001_001.png  Cardiomegaly|Emphysema           1           58  1  0  1   
2  00000001_002.png   Cardiomegaly|Effusion           1           58  1  0  1   
3  00000002_000.png              No Finding           2           80  1  0  1   
4  00000003_000.png                  Hernia           3           81  0  1  1   

  AP  
0  0  
1  0  
2  0  
3  0  
4  0

In [91]:
df2.dropna(inplace = True)
df2.head()

Image Index          Finding Labels  Patient ID  Patient Age  M  F PA  \
0  00000001_000.png            Cardiomegaly           1           57  1  0  1   
1  00000001_001.png  Cardiomegaly|Emphysema           1           58  1  0  1   
2  00000001_002.png   Cardiomegaly|Effusion           1           58  1  0  1   
3  00000002_000.png              No Finding           2           80  1  0  1   
4  00000003_000.png                  Hernia           3           81  0  1  1   

  AP  
0  0  
1  0  
2  0  
3  0  
4  0

In [92]:
df3 = df2
df3[["Classification", "Nonsense"]] = df2["Finding Labels"].str.split('|', 1, expand = True)
df3.drop(["Nonsense", "Finding Labels"], axis = 1, inplace = True)
df3.head()

Image Index  Patient ID  Patient Age  M  F PA AP Classification
0  00000001_000.png           1           57  1  0  1  0   Cardiomegaly
1  00000001_001.png           1           58  1  0  1  0   Cardiomegaly
2  00000001_002.png           1           58  1  0  1  0   Cardiomegaly
3  00000002_000.png           2           80  1  0  1  0     No Finding
4  00000003_000.png           3           81  0  1  1  0         Hernia

In [94]:
df3["Classification"] = df3[["Classification"]].apply(LabelEncoder().fit_transform)
df3.head()

Image Index  Patient ID  Patient Age  M  F PA AP  Classification
0  00000001_000.png           1           57  1  0  1  0               1
1  00000001_001.png           1           58  1  0  1  0               1
2  00000001_002.png           1           58  1  0  1  0               1
3  00000002_000.png           2           80  1  0  1  0              10
4  00000003_000.png           3           81  0  1  1  0               7

### Train/Test

In [196]:
Y = df3["Classification"]
classes = len(df3.Classification.unique())
test_size = 0.2

x = data
z = df3[["PA", "AP"]] # "Patient Age", "M", "F", "PA", "AP"
y = tf.keras.utils.to_categorical(Y)

x_train, x_test, z_train, z_test, y_train, y_test = \
sklearn.model_selection.train_test_split(x, z, y, test_size = test_size, random_state = 0)

### Model 1: DNN

#### Model structure

In [230]:
X_img = tf.keras.Input(shape = (px, px, 3, ))
img1 = tf.keras.layers.Flatten()(X_img)
img2 = tf.keras.layers.Dense(1000, activation = 'relu')(img1)
d1 = tf.keras.layers.Dropout(0.4)(img2)
img3 = tf.keras.layers.Dense(500, activation = 'relu')(d1)
d2 = tf.keras.layers.Dropout(0.4)(img3)
img4 = tf.keras.layers.Dense(100, activation = 'relu')(d2)
d3 = tf.keras.layers.Dropout(0.4)(img4)

X_num = tf.keras.Input(shape = (2, ))
num1 = tf.keras.layers.Dense(1000, activation = 'relu')(X_num)
d4 = tf.keras.layers.Dropout(0.4)(num1)
num2 = tf.keras.layers.Dense(500, activation = 'relu')(d4)
d5 = tf.keras.layers.Dropout(0.4)(num2)
num3 = tf.keras.layers.Dense(100, activation = 'relu')(d5)
d6 = tf.keras.layers.Dropout(0.4)(num3)

conc = tf.keras.layers.concatenate([d3, d6])

out = tf.keras.layers.Dense(15, activation = 'softmax')(conc)
dnn = tf.keras.Model(inputs = [X_img, X_num], outputs = out)
dnn.summary()

Model: "model_41"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_76 (InputLayer)           [(None, 32, 32, 3)]  0                                            
__________________________________________________________________________________________________
flatten_49 (Flatten)            (None, 3072)         0           input_76[0][0]                   
__________________________________________________________________________________________________
input_77 (InputLayer)           [(None, 2)]          0                                            
__________________________________________________________________________________________________
dense_233 (Dense)               (None, 1000)         3073000     flatten_49[0][0]                 
___________________________________________________________________________________________

#### Compile the model

In [231]:
cb = tf.keras.callbacks.EarlyStopping(monitor = 'val_loss', patience = 5)
solver = tf.keras.optimizers.Adam(learning_rate = 0.001)
loss = tf.keras.losses.CategoricalCrossentropy()
dnn.compile(loss = loss, optimizer = solver, metrics = ['accuracy'])

#### Train the model

In [232]:
dnn_hist = dnn.fit([x_train, z_train], y_train, batch_size = 100, epochs = 10, validation_split = 0.25, callbacks = [cb])

Train on 3000 samples, validate on 1000 samples
Epoch 1/10
3000/3000 [==============================] - 2s 720us/sample - loss: 7.7593 - accuracy: 0.5180 - val_loss: 7.0758 - val_accuracy: 0.5610
Epoch 2/10
3000/3000 [==============================] - 2s 615us/sample - loss: 7.3241 - accuracy: 0.5453 - val_loss: 7.0758 - val_accuracy: 0.5610
Epoch 3/10
3000/3000 [==============================] - 2s 582us/sample - loss: 7.2478 - accuracy: 0.5503 - val_loss: 7.0758 - val_accuracy: 0.5610
Epoch 4/10
3000/3000 [==============================] - 2s 589us/sample - loss: 7.2585 - accuracy: 0.5497 - val_loss: 7.0758 - val_accuracy: 0.5610
Epoch 5/10
3000/3000 [==============================] - 2s 631us/sample - loss: 7.2317 - accuracy: 0.5513 - val_loss: 7.0758 - val_accuracy: 0.5610
Epoch 6/10
3000/3000 [==============================] - 2s 669us/sample - loss: 7.2465 - accuracy: 0.5503 - val_loss: 7.0758 - val_accuracy: 0.5610


In [235]:
yhat_dnn = dnn.predict([x_test, z_test])
ytest_actual = np.argmax(a=y_test, axis = 1)
ytest_pred_dnn = np.argmax(a=yhat_dnn, axis = 1)
print('\nConfusion matrix:\n',sklearn.metrics.confusion_matrix(ytest_actual, ytest_pred_dnn) )
print('\nAccuracy score:', sklearn.metrics.accuracy_score(ytest_actual, ytest_pred_dnn))


Confusion matrix:
 [[  0   0   0   0   0   0   0   0   0   0  92   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  45   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  33   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   9   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  63   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  20   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  27   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   3   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  81   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  11   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0 560   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  17   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  14   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   2   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  23   0   0   0   0]]

Accuracy score: 0.56


### Model 2: CNN

In [212]:
x_img = tf.keras.layers.Input(shape = (px,px,3)) 
conv1 = tf.keras.layers.Conv2D(32, (3, 3), strides=2, activation='relu', input_shape=(px, px, 3))(x_img) 
pool1 = tf.keras.layers.MaxPooling2D(pool_size=(3, 3), strides=1)(conv1) 
pool2 = tf.keras.layers.AveragePooling2D(pool_size = (3,3), strides = 1)(conv1)
pool_conc = tf.keras.layers.concatenate([pool1, pool2], axis = 1) 
conv2 = tf.keras.layers.Conv2D(128, (3,3), strides = 2, activation = 'relu',use_bias = False, kernel_initializer = 'glorot_uniform')(pool_conc) 
flatten =tf.keras.layers.Flatten()(conv2)
img1 = tf.keras.layers.Dense(1000, activation='relu', kernel_initializer='glorot_uniform')(flatten)
di1 = tf.keras.layers.Dropout(0.4)(img1)
img2 = tf.keras.layers.Dense(500, activation = 'relu')(di1)
di2 = tf.keras.layers.Dropout(0.4)(img2)
img3 = tf.keras.layers.Dense(200, activation = 'relu', kernel_initializer = 'glorot_uniform')(di2)
di3 = tf.keras.layers.Dropout(0.4)(img3)

out = tf.keras.layers.Dense(15, activation='softmax')(di3) 

cnn = tf.keras.Model(inputs = x_img, outputs = out)
cnn.summary()

Model: "model_38"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_71 (InputLayer)           [(None, 32, 32, 3)]  0                                            
__________________________________________________________________________________________________
conv2d_34 (Conv2D)              (None, 15, 15, 32)   896         input_71[0][0]                   
__________________________________________________________________________________________________
max_pooling2d_17 (MaxPooling2D) (None, 13, 13, 32)   0           conv2d_34[0][0]                  
__________________________________________________________________________________________________
average_pooling2d_17 (AveragePo (None, 13, 13, 32)   0           conv2d_34[0][0]                  
___________________________________________________________________________________________

#### Compile the model

In [214]:
adam = tf.keras.optimizers.Adam(lr=0.0001)
loss=tf.keras.losses.CategoricalCrossentropy()
cnn.compile(loss=loss, optimizer=adam, metrics=['accuracy'])

#### Train the model

In [215]:
callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=5)
cnn_history = cnn.fit(x_train, y_train, batch_size=100, epochs=10, validation_split=0.2, callbacks=[callback]) 

Train on 3200 samples, validate on 800 samples
Epoch 1/10
3200/3200 [==============================] - 6s 2ms/sample - loss: 7.3635 - accuracy: 0.5403 - val_loss: 7.0315 - val_accuracy: 0.5638
Epoch 2/10
3200/3200 [==============================] - 5s 2ms/sample - loss: 7.2189 - accuracy: 0.5519 - val_loss: 7.0315 - val_accuracy: 0.5638
Epoch 3/10
3200/3200 [==============================] - 5s 2ms/sample - loss: 7.2280 - accuracy: 0.5516 - val_loss: 7.0315 - val_accuracy: 0.5638
Epoch 4/10
3200/3200 [==============================] - 5s 2ms/sample - loss: 7.2128 - accuracy: 0.5525 - val_loss: 7.0315 - val_accuracy: 0.5638
Epoch 5/10
3200/3200 [==============================] - 6s 2ms/sample - loss: 7.2213 - accuracy: 0.5519 - val_loss: 7.0315 - val_accuracy: 0.5638
Epoch 6/10
3200/3200 [==============================] - 6s 2ms/sample - loss: 7.2160 - accuracy: 0.5522 - val_loss: 7.0315 - val_accuracy: 0.5638
Epoch 7/10
3200/3200 [==============================] - 6s 2ms/sample - loss:

#### Accuracy score

In [220]:
yhat_cnn = cnn.predict(x_test)
ytest_actual = np.argmax(a=y_test, axis = 1)
ytest_pred_cnn = np.argmax(a=yhat, axis = 1)
print('\nConfusion matrix:\n',sklearn.metrics.confusion_matrix(ytest_actual, ytest_pred_cnn) )
print('\nAccuracy score:', sklearn.metrics.accuracy_score(ytest_actual, ytest_pred_cnn))


Confusion matrix:
 [[  0   0   0   0   0   0   0   0   0   0  92   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  45   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  33   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   9   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  63   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  20   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  27   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   3   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  81   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  11   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0 560   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  17   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  14   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   2   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  23   0   0   0   0]]

Accuracy score: 0.56


### Model 3: CNN + DNN

#### Model structure

In [224]:
x_img = tf.keras.layers.Input(shape = (px,px,3)) 
conv1 = tf.keras.layers.Conv2D(32, (3, 3), strides=2, activation='relu', input_shape=(px, px, 3))(x_img) 

pool1 = tf.keras.layers.MaxPooling2D(pool_size=(3, 3), strides=1)(conv1) 
pool2 = tf.keras.layers.AveragePooling2D(pool_size = (3,3), strides = 1)(conv1)
pool_conc = tf.keras.layers.concatenate([pool1, pool2], axis = 1) 

conv2 = tf.keras.layers.Conv2D(128, (3,3), strides = 2, activation = 'relu',use_bias = False, kernel_initializer = 'glorot_uniform')(pool_conc) 
flatten =tf.keras.layers.Flatten()(conv2)

img1 = tf.keras.layers.Dense(1000, activation='relu', kernel_initializer='glorot_uniform')(flatten)
di1 = tf.keras.layers.Dropout(0.4)(img1)
img2 = tf.keras.layers.Dense(500, activation = 'relu')(di1)
di2 = tf.keras.layers.Dropout(0.4)(img2)
img3 = tf.keras.layers.Dense(200, activation = 'relu', kernel_initializer = 'glorot_uniform')(di2)
di3 = tf.keras.layers.Dropout(0.4)(img3)

x_num = tf.keras.layers.Input(shape = (2, ))  
num1 = tf.keras.layers.Dense(1000, activation = 'relu')(x_num)
d1 = tf.keras.layers.Dropout(0.4)(num1)
num2 = tf.keras.layers.Dense(500, activation = 'relu')(d1)
d2 = tf.keras.layers.Dropout(0.4)(num2)
num3 = tf.keras.layers.Dense(200, activation = 'relu')(d2)
d3 = tf.keras.layers.Dropout(0.4)(num3)

conc = tf.keras.layers.concatenate([di3, d3])

out = tf.keras.layers.Dense(15, activation='softmax')(conc) 


cd = tf.keras.Model(inputs = [x_img, x_num], outputs = out)
cd.summary()

Model: "model_40"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_74 (InputLayer)           [(None, 32, 32, 3)]  0                                            
__________________________________________________________________________________________________
conv2d_38 (Conv2D)              (None, 15, 15, 32)   896         input_74[0][0]                   
__________________________________________________________________________________________________
max_pooling2d_19 (MaxPooling2D) (None, 13, 13, 32)   0           conv2d_38[0][0]                  
__________________________________________________________________________________________________
average_pooling2d_19 (AveragePo (None, 13, 13, 32)   0           conv2d_38[0][0]                  
___________________________________________________________________________________________

#### Compile the model

In [225]:
adam = tf.keras.optimizers.Adam(lr=0.001)
loss=tf.keras.losses.CategoricalCrossentropy()
cd.compile(loss=loss, optimizer=adam, metrics=['accuracy'])

#### Train the model

In [226]:
callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=5)
cd_history = cd.fit([x_train, z_train], y_train, batch_size=100, epochs=10, validation_split=0.2, callbacks=[callback]) 

Train on 3200 samples, validate on 800 samples
Epoch 1/10
3200/3200 [==============================] - 6s 2ms/sample - loss: 7.6777 - accuracy: 0.5209 - val_loss: 7.0315 - val_accuracy: 0.5638
Epoch 2/10
3200/3200 [==============================] - 6s 2ms/sample - loss: 7.2128 - accuracy: 0.5525 - val_loss: 7.0315 - val_accuracy: 0.5638
Epoch 3/10
3200/3200 [==============================] - 6s 2ms/sample - loss: 7.2128 - accuracy: 0.5525 - val_loss: 7.0315 - val_accuracy: 0.5638
Epoch 4/10
3200/3200 [==============================] - 6s 2ms/sample - loss: 7.2128 - accuracy: 0.5525 - val_loss: 7.0315 - val_accuracy: 0.5638
Epoch 5/10
3200/3200 [==============================] - 6s 2ms/sample - loss: 7.2128 - accuracy: 0.5525 - val_loss: 7.0315 - val_accuracy: 0.5638
Epoch 6/10
3200/3200 [==============================] - 6s 2ms/sample - loss: 7.2128 - accuracy: 0.5525 - val_loss: 7.0315 - val_accuracy: 0.5638
Epoch 7/10
3200/3200 [==============================] - 6s 2ms/sample - loss:

#### Accuracy

In [228]:
yhat = cd.predict([x_test, z_test])
ytest_actual = np.argmax(a=y_test, axis = 1)
ytest_pred_cd = np.argmax(a=yhat, axis = 1)
print('\nConfusion matrix:\n', sklearn.metrics.confusion_matrix(ytest_actual, ytest_pred_cd))
print('\nAccuracy score:', sklearn.metrics.accuracy_score(ytest_actual, ytest_pred_cd))


Confusion matrix:
 [[  0   0   0   0   0   0   0   0   0   0  92   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  45   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  33   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   9   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  63   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  20   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  27   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   3   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  81   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  11   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0 560   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  17   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  14   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   2   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  23   0   0   0   0]]

Accuracy score: 0.56
